---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: display repo
  image: node
  commands:
    - apt install tree -y
    - tree .

- name: build
  image: plugins/docker
  settings:
    password:
      from_secret: QUAY_PWORD
    registry: quay.io
    repo: quay.io/calvinrodo/terraformpresentation
    tags:
      - latest
    username: calvinrodo+presentations