---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build and push to quay.io
  image: plugins/docker
  settings:
    password:
      from_secret: QUAY_PWORD
    registry: quay.io
    repo: quay.io/calvinrodo/terraformpresentation
    tags:
      - latest
    username: calvinrodo+presentations
- name: slack
  image: plugins/slack
  settings:
    webhook: 
      from_secret: SLACK_WEBHOOK
    channel: ci
    link_names: true
    username: "cloud.drone.io"
    template: >
      {{#success build.status}}
        Terraform presentation build {{build.number}} succeeded. Good job. <@Cal>
      {{else}}
        Terraform presentation build {{build.number}} failed. You suck <@Cal> 
      {{/success}}